# -*- coding: utf-8 -*-
"""UsingAPIstock.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K2DbVtedaEJ6tvXsCV1_dWgaiJZtwjSI

# An examle of using an API to get the stock prices
"""

#!pip install pycoingecko
# importing the library for the API
from pycoingecko import CoinGeckoAPI
import pandas as pd
import matplotlib.pyplot as plt

cq = CoinGeckoAPI()
bitcoin_data = cq.get_coin_market_chart_by_id(id = 'bitcoin', vs_currency='usd',days = 30)

print(type(bitcoin_data)) # so the response is a dict
print(f"The keys from the respnse is {bitcoin_data.keys()}")

bitcoin_data_prices = bitcoin_data['prices']
print(type(bitcoin_data_prices), len(bitcoin_data_prices[0]))
df = pd.DataFrame(bitcoin_data_prices,columns=['TimeStamp', 'Price']) # converting into a dataframe
print(df.head())

df['Date'] = pd.to_datetime(df['TimeStamp'], unit='ms')
print(df['Date'])

groupData = df.groupby(df.Date.dt.date).agg({'Price': ['min','max','first','last']})
print(groupData)

df.set_index('Date')
plt.plot(df.Date, df.Price)